version: '3.4'
services:
# NodeJS App
 web:
  image: wakecap
  container_name: ultimate-mongodb
  build: .
  environment:
    NODE_ENV: production
  ports:
   - 3000:3000
  links:
   - mongodb
  command: npm start
 
 
 # MongoDB
 mongodb:
  image: mongo
  container_name: ultimate-mongodb
  ports:
   - 27017:27017

    
